# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# The locale of the site.
site.locale: en-US
# The title of the site.
title: Yeshwanth Neriyanuri
# The subtitle of the site.
# subtitle:
# The name of the site owner.
name: Yeshwanth Sharma Neriyanuri
# The email of the site owner.
email: hithisisyeshwanth@gmail.com
# The description of the site.
description: >- # this means to ignore newlines until "baseurl:"
  Software Engineer specializing in Machine Learning, AI, and Distributed Systems. Passionate about software craftsmanship and building high-performance solutions.
# The title of the masthead.
# masthead_title:
# Whether to show breadcrumbs.
breadcrumbs: true
# The average number of words per minute for reading time calculation.
words_per_minute: 250
# Whether to enable the copy code button.
enable_copy_code_button: true
# The URL of the site.
url: "https://hithisisyeshwanth.github.io"
# The repository of the site.
repository: "https://www.github.com/hithisisyeshwanth"
# The GitHub username of the site owner.
github_username: hithisisyeshwanth
# The skin of the Minimal Mistakes theme.
minimal_mistakes_skin: dark
# Whether to enable search.
search: true


# Build settings
# The Markdown processor.
markdown: kramdown
# The remote theme to use.
remote_theme: mmistakes/minimal-mistakes
# Outputting
# The permalink structure for posts.
permalink: /:categories/:title/
# The number of posts to show per page.
paginate: 5 # amount of posts to show
# The path for paginated pages.
paginate_path: /page:num/
# The timezone of the site.
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# The files and directories to include in the build.
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
# The plugins to use.
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# The author information.
author:
  name: "Yeshwanth Neriyanuri"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Mastering the craftsmanship of software engineering, one elegant line of code at a time."
  location: "Bengaluru, India"
  email: hithisisyeshwanth@gmail.com
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hithisisyeshwanth/hithisisyeshwanth.github.io"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://in.linkedin.com/in/yeshwanth-sharma-neriyanuri-3a9590a3"

# The footer links.
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

# The default settings for documents.
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: "_projects"
      type: posts
    values:
      layout: single
      author_profile: true

# The settings for the category archive.
category_archive:
  type: liquid
  path: /categories/
# The settings for the tag archive.
tag_archive:
  type: liquid
  path: /tags/

